### ISSUE TITLE
Display storage usage by per-storage host with user/project-based

### ISSUE THREAD

**Issue by agatha197** [lablup/backend.ai-webui#1714]
In vfolder v3, we need to migrate per-vfolder quota mgmt. to per-user & per-project quota mgmt. So we need the below UIs.

- [ ] Storage host and volume view
- [ ] Visualize how much usage is for each storage host in the storage host selection menu when creating a folder.![https://github.com/lablup/backend.ai-webui/assets/28584164/9cb83cf6-fc07-406c-b363-7d70cc0a7625](https://github.com/lablup/backend.ai-webui/assets/28584164/9cb83cf6-fc07-406c-b363-7d70cc0a7625)
- [x] If the backend can use quota info, let's add the usage / quota pie graph of storage hosts.\* The usage and quota info is more important than the number of folders.
- The storage status graph size seems to be too large, so it is better to reduce it.![https://github.com/lablup/backend.ai-webui/assets/28584164/2c62b587-eed6-45e9-8199-1ce84df81fdf](https://github.com/lablup/backend.ai-webui/assets/28584164/2c62b587-eed6-45e9-8199-1ce84df81fdf)

- [ ] Display filesystem level usage information on the storage host itself
- [x] Setting UI for admin
  {code:[tasklist]}
### Tasks
- [ ] https://github.com/lablup/backend.ai-webui/issues/1742

{code}

**Comment by agatha197** [comment]
resolved by https://github.com/lablup/backend.ai-webui/issues/1712
