### ISSUE TITLE
Storage setting UI for admin (per project / per user)

### ISSUE THREAD

**Issue by Sujin-Kim1** [lablup/backend.ai-webui#1742]
```[tasklist]
### Tasks
- [x] Adding user selector
- [x] Adding project selector
- [x] Get / set quota setting
- [x] Fill up the input with default / custom value when clicking the edit button (quota setting)
```

**Comment by Sujin-Kim1** [comment]
how to get props from the web component to react component?

**Comment by Sujin-Kim1** [comment]
Skeleton UI
![Image](https://github.com/lablup/backend.ai-webui/assets/28584164/0ca03abd-8842-4037-9024-e535cbe94dd0)

**Comment by Sujin-Kim1** [comment]
complete data integration with graphql

**Comment by Sujin-Kim1** [comment]
Progress:
I have struggled with routing the storage setting page. I set the setting page url to `agent/storage/:<storage host id>`. And if I passed the `storage host id`, the agent page appears. So I just set the setting url to `storage-settings` for testing and I got the data from the url successfully(handled the `storage host id`). 

Plan:
- Change the url of storage setting page.
- CRUD the quota info.

**Comment by Sujin-Kim1** [comment]
I'm struggling with this error.
<img width="2498" alt="image" src="https://github.com/lablup/backend.ai-webui/assets/28584164/5cdfc303-32ab-4c4b-bac7-e15ebf57f826">

**Comment by Sujin-Kim1** [comment]
Problems
- when the resource policy is updated, the project/user selector and menu come out for a while and disappear.
- need to refresh when changing the volume. It is empty page when changing the volume.

**Comment by Sujin-Kim1** [comment]
Final UI
<img width="1233" alt="image" src="https://github.com/lablup/backend.ai-webui/assets/28584164/483c2d2f-2f7a-4163-8711-bd5453b3fb16">
