### ISSUE TITLE
Create modal component for creating service on model-serving page

### ISSUE THREAD

**Issue by lizable** [lablup/backend.ai-webui#1746]
In order to implement model service creation UI, I need to implement almost everything we already implemented in session launcher to React.

It's a bit cumbersome, but I think it's worth it.

Here's the list that I need to provide to users to create model service.

1. scaling-group
    - select UI
    - only show items(scaling group) that supports "wsproxy v2(token api key and wsproxy address is not null)"
1. vfolder (for model service)
    - temporally show with select UI (since we cannot select multiple model type vfolders in this phase)
    - only show items with "model type"
1. image + architecture / version
    - select UI
1. name
    - input field UI
1. resources
    - slider (maybe?) + input field UI
1. desired session count
    - input field UI
1. open to public
    - switch UI
    - default value is `False`
```[tasklist]
### Tasks
- [x] 1 RC(React Component): ResourceGroupSelect with support option
- [x] 2 RC: VFolderSelector with type option
- [x] 3 RC: Image + Architecture / version Select
```

**Comment by lizable** [comment]
FYI @yomybaby

**Comment by yomybaby** [comment]
resovled by #1801 and #1820
