### ISSUE TITLE
Let's refactor app-launcher to show app information according to opened port

### ISSUE THREAD

**Issue by lizable** [lablup/backend.ai-webui#1755]
### Main idea

Related: #1753.
For now, we only show the app launcher with the supported app with icon and name,
but I think it's better to display the port number, too.

```[tasklist]
### Tasks
- [ ] Add `lablup-expansion` for the pre-opened ports on the app dialog
- [ ] App name will be the port number.
- [ ] (Option) Change the app icon
```

**Comment by Sujin-Kim1** [comment]
When `preopen_ports` is set, current session app dialog displays the preopen ports as below. And we can judge them through the protocol (protocol of service_ports is preopen). So we can display the preopen ports and mapped app together with [Collapse](https://ant.design/components/collapse) and [List](https://ant.design/components/list) component or other ways.
![image](https://github.com/lablup/backend.ai-webui/assets/28584164/2466e473-90e6-4ab0-b38b-bf2914e53558)

**Comment by Sujin-Kim1** [comment]
resolved by #1854
