### ISSUE TITLE
Configurable bind host and port for craco server

### ISSUE THREAD

**Issue by kyujin-cho** [lablup/backend.ai-webui#1779]
### Main idea

On our current NPM script, when starting create-react-app server by executing `craco start`, the server always binds to `127.0.0.1:3081` as this value is hardcoded to `react/.env.development` file.
<img width="637" alt="Screenshot 2023-07-13 at 7 41 59 PM" src="https://github.com/lablup/backend.ai-webui/assets/2904494/d6cb028f-0ced-4f12-9f27-59fb37c7405d">
Let's find out a way for user to override this behaviour, by passing their own `HOST` and `PORT` variable when starting server.

```[tasklist]
### Tasks
- [x] change port number so that developer can connect to the same port
- [ ] test on a remote environment
- [x] update README.md to guide how to change the port and host
```
