### ISSUE TITLE
Update `Dockerfile` and `docker-compose.yml` to build development server

### ISSUE THREAD

**Issue by Choi-Jiwon-38** [lablup/backend.ai-webui#1805]
### Main idea

This issue is derived from closed issue #1795 .

The current build method with Docker does not work with duplicated library [backend.ai-webserver](https://github.com/lablup/backend.ai-webserver)

We have to rewrite `Dockerfile` and `docker-compose.yml` files to build development server!

```[tasklist]
### Tasks
- [x] [goal] split `build:d` command to `react-side` and `lit-side` so that can be execution in each container
- [x] [goal] Make port number configurable
- [x] [error] none proxy response
```
