### ISSUE TITLE
Refactor Manage Apps dialog (environment page)

### ISSUE THREAD

**Issue by Sujin-Kim1** [lablup/backend.ai-webui#1810]
### Main idea

Let's refactor Manager Apps dialog like session environment setting dialog.

```[tasklist]
- [ ] Place `Add` button at the bottom.
- [ ] Finish -> Save
- [ ] Add reset button if possible
```

<img width="719" alt="image" src="https://github.com/lablup/backend.ai-webui/assets/28584164/2359217f-3de4-47be-8709-9ce66779dd0b">

Reference
<img width="499" alt="image" src="https://github.com/lablup/backend.ai-webui/assets/28584164/4a97d5a7-ea3c-4c7c-bcf6-7d348c1f026e">

### Anything else?

You can make it as a react component
```[tasklist]
### Tasks
- [x] skeleton UI
- [ ] add, modify features
```

**Comment by agatha197** [comment]
resolved by https://github.com/lablup/backend.ai-webui/pull/2265
