### ISSUE TITLE
Let's allow import private github / gitlab repository

### ISSUE THREAD

**Issue by agatha197** [lablup/backend.ai-webui#1913]
### Main idea

We can only import public github / gitlab repository. Let's also allow import private repositories too.It will need to update the core.

```Java
### Tasks
- [ ] Add modal to set id, token, (2FA if needed) of github / gitlab
- [ ] Import private repository using token.
- [ ] Update the backend.ai core to perform this feature.
```

### Anything else?

ref: https://docs.github.com/en/free-pro-team@latest/rest/repos/contents?apiVersion=2022-11-28#download-a-repository-archive-zip

JIRA Issue: FR-93
