### ISSUE TITLE
Let’s add inactivelist

### ISSUE THREAD

**Issue by agatha197** [lablup/backend.ai-webui#1938]
### Main idea

Currently, the `blocklist` option is disabled in the sidebar menu and is supposed to be taken to the error page when accessing the page in url. However, some people may want to hide the options on the blocklist from the sidebar menu altogether. So, let's add an inactivelist so that pages belonging to the blocklist are completely hidden in the sidebar menu, and pages belonging to the inactivelist are disabled like the existing blocklist.

```[tasklist]
### Tasks
- [ ] add inactivelist
- [ ] hide blocklist page in the blocklist
- [ ] disable inactive page in the inactivelist
- [ ] both of them, it is disallowed to access by url.
```
