### ISSUE TITLE
Neo Session Launcher - Beta

### ISSUE THREAD

**Issue by yomybaby** [lablup/backend.ai-webui#2025]
Let's move forward to BETA! We need to complete the following tasks in the [alpha version](https://github.com/lablup/backend.ai-webui/pull/1953).

> [!IMPORTANT]
> If you add a task to the list below, please also leave your name so others know who created it.

```[tasklist]
### 💪 Tasks
- [ ] https://github.com/lablup/backend.ai-webui/pull/2026
- [x] `ResouceAllocationFormItems`: Consideration of the `alwaysEnqueueComputeSession` option https://github.com/lablup/backend.ai-webui/pull/2030
- [x] `ResouceAllocationFormItems`: improve UX related to min/max limit and remaining (min shmem 64 and image limit, etc.) https://github.com/lablup/backend.ai-webui/pull/2030
- [x] `ResouceAllocationFormItems`: setting values in accelerator value to zero(0) considering the image doesn't support AI accelerato, [comment by @lizable ](https://github.com/lablup/backend.ai-webui/pull/2026#discussion_r1394062070) https://github.com/lablup/backend.ai-webui/pull/2030
- [x] [Preset] Auto selection
- [x] [Preset] Config option to hide custom preset
- [ ] Session template & recent history (including handling not available resources)
- [x] "No mount vfolder" confirm modal
- [ ] Form item to change session owner (admin only)
- [ ] Session launcher modes: Inference and Import
- [x] Display remain time until batch scheduledDate
- [x] Display an appropriate error message when a session fails to start.
```

```[tasklist]
### 🏝️ Lower-priority tasks
- [ ] VFolder Table(In `Form.Item`) using GraphQL pagination, filter, order, etc. (filter and setting components)
- [ ] Save as a session template
```

```[tasklist]
### 🐞 Bugs
- [x] If a URL has a selected image, the image type does not change automatically based on the image limit. (reported by jongeun)
- [ ] https://github.com/lablup/backend.ai-webui/pull/2029
```

**Comment by yomybaby** [comment]
Since 24.03, the Neo session launcher is set as the default launcher. Remaining tasks in the above list will be addressed in other issues.
