### ISSUE TITLE
Style: Let's improve session status info style

### ISSUE THREAD

**Issue by agatha197** [lablup/backend.ai-webui#2148]
### Main idea

```[tasklist]
### Tasks
- [x] Let's remove the left padding of the session info text.
- [x] Let's remove the title if the detail contents are empty.
- [x] Set 'Predicate Checks' to open by default.
- [x] Let's increase left padding of the contents.
```

- Let's remove the left padding of the session info text.
<img width="466" alt="Pasted Graphic 3" src="https://github.com/lablup/backend.ai-webui/assets/28584164/9a923273-c465-4e29-b7b3-cb63a9927ed5">
<img width="719" alt="Your keypair resource quota is" src="https://github.com/lablup/backend.ai-webui/assets/28584164/0b0eb094-a483-4fab-b026-1bbc83f543de">

- Let's remove the title if the detail contents are empty.
<img width="466" alt="Pasted Graphic 5" src="https://github.com/lablup/backend.ai-webui/assets/28584164/cd6f3e96-b817-4fa9-85a7-775bd0d38f59">

- Set 'Predicate Checks' to open by default.
- Let's increase left padding of the contents. The value of the left padding must have the same padding value for all contents.
<img width="466" alt="Pasted Graphic 6" src="https://github.com/lablup/backend.ai-webui/assets/28584164/fffdfc65-8703-4452-a779-1e4c5eef8ac0">
