### ISSUE TITLE
Apply "render as you fetch" pattern

### ISSUE THREAD

**Issue by yomybaby** [lablup/backend.ai-webui#2159]
With Relay and react-router data API, we can apply the "render as you fetch" pattern to several parts of WebUI to improve UX.

```Java
### Tasks
- [ ] to pages using react-router data api
- [ ] to modals
- [ ] to the header
- [ ] to the sider
```

JIRA Issue: FR-77
