### ISSUE TITLE
Refactoring summary page

### ISSUE THREAD

**Issue by agatha197** [lablup/backend.ai-webui#2170]
### Main idea

```Java
### Tasks
- [ ] Let's change summary page to React component.
- [ ] Every panel is movable.
- [ ] Every panel is removable.
- [ ] Every panel is resizable.
- [ ] The height and width of panels is multiple size of grid. (see the image below)
- [ ] In the footer, it can include some link such as upload files, webui app download link, etc.
```

### Anything else?

Please ref [aws](https://ap-northeast-2.console.aws.amazon.com/console/home?region=ap-northeast-2) page!

- The height and width of panels is multiple size of grid.

- movable, removable, resizable, and it has own grid size.

JIRA Issue: FR-75
