### ISSUE TITLE
Setting configs in UI

### ISSUE THREAD

**Issue by agatha197** [lablup/backend.ai-webui#2187]
### Main idea

Some configs are handled in localStorage(compact sidebar, language, etc.), and the others(maskUserInfo, apiEndpoint, siteDescription, etc) are handled in `config.toml`. Let's unify these configs and make superadmin possible to modify in UI.

For this issue, let's add [JSON Schema](https://json-schema.org/) for setting default value and types, etc for this config file. With JSON Schema, we can validate config files as well as add the [badge](https://ant.design/components/badge) to the modified configs.

```Java
### Tasks
- [ ] Let's add JSON schema files to validate config files. It includes default value and type, description, validation rule and etc.
- [ ] Display the set values on `usersettings` page.
- [ ] If the value is changed, let's add the [badge](https://ant.design/components/badge) so that the user can notice that the setting does not use the default value.
- [ ] If the value is changed, it influences the UI right away. For instance, if the user turns on the compact sidebar, the sidebar will be collapsed without refreshing.
```

### Alternative ideas

Feedback is welcome. You can freely modify the upper idea in proceeding to the above task.

### Anything else?

You can reference VS Code Setting. The modified one is represented with a bar.![https://github.com/lablup/backend.ai-webui/assets/28584164/f7b1bb7d-ccd2-4ad4-963e-702d284474d5](https://github.com/lablup/backend.ai-webui/assets/28584164/f7b1bb7d-ccd2-4ad4-963e-702d284474d5)

- toml to json:  https://transform.tools/toml-to-json
- json to json-schema: https://transform.tools/json-to-json-schema

JIRA Issue: FR-74
