### ISSUE TITLE
Let's refactor user-list at credential page

### ISSUE THREAD

**Issue by gee05053** [lablup/backend.ai-webui#2216]
### Main idea

Currently, user-list at credential page is implemented by Lit element.
But UserInfoModal, UserSettingModal is implemented by React.

Let's refactor user-list using react and implement new component that is implemented by Lit element.
And I will apply UserNode object.

![스크린샷 2024-02-15 오후 2 10 20](https://github.com/lablup/backend.ai-webui/assets/28584221/3519f024-fd98-4024-9a8c-fd5804854671)
![스크린샷 2024-02-15 오후 2 10 24](https://github.com/lablup/backend.ai-webui/assets/28584221/b95f9bad-715a-4519-b43f-2d6e113e390f)

```[tasklist]
### Tasks
- [x] Use `user_nodes` to fetch the user list
- [x] The pagination UI using `user_nodes`'s arguments
- [x] The filter UI using `user_nodes`'s arguments
- [x] Backward compatibility ( `>= 24.03.*` uses new user list)
```

**Comment by yomybaby** [comment]
@gee05053  I added the task list to the description. Please check it.
