### ISSUE TITLE
Update wsproxy with newest version

### ISSUE THREAD

**Issue by inureyes** [lablup/backend.ai-webui#58]
* Update wsproxy with newest version
 * As a  git submodule

## TODO 
 * [x] Match configuration with console
 * [x] App-specific runtime
 * [x] Runtime test with electron shell
